# Example Deployment using a config map as input for a template
# which is processed from an init-container
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    project: k8spatterns
    pattern: Controller
  name: expose-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        project: k8spatterns
        pattern: Controller
    spec:
      containers:
      - name: kubeapi-proxy
        image: k8spatterns/kubeapi-proxy
      - name: expose-controller
        image: k8spatterns/curl-jq
        command:
        - "sh"
        - "/expose-script/expose-controller.sh"
        volumeMounts:
        - mountPath: "/expose-script"
          name: expose-controller-script
      volumes:
      - name: expose-controller-script
        configMap:
          name: expose-controller-script
      serviceAccountName: expose-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: expose-controller
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: expose-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: expose-controller
subjects:
- kind: ServiceAccount
  name: expose-controller
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: expose-controller
rules:
- apiGroups: [""]
  resources:
  - services
  verbs: ["watch", "list"]
- apiGroups: ["extensions"]
  resources:
  - ingresses
  verbs: ["create", "list", "update"]
